# Generated by Django 2.1 on 2018-08-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('first_names', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('participant_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Participant ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('identifier', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StageSurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hci.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='StageSurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hci.Stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hci.Participant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hci.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='stagesurveyanswer',
            name='stage_survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hci.StageSurveyQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='stagetaskresult',
            unique_together={('participant', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='stagesurveyquestion',
            unique_together={('stage', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='stagesurveyanswer',
            unique_together={('stage_survey_question', 'participant')},
        ),
    ]
