# Generated by Django 2.1 on 2018-08-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('participant_id',)},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('identifier',)},
        ),
        migrations.AlterModelOptions(
            name='stagesurveyanswer',
            options={'ordering': ('participant', 'stage_survey_question')},
        ),
        migrations.AlterModelOptions(
            name='stagesurveyquestion',
            options={'ordering': ('stage', 'identifier')},
        ),
        migrations.AlterModelOptions(
            name='stagetaskresult',
            options={'ordering': ('participant', 'stage')},
        ),
    ]
