# Generated by Django 2.1 on 2018-09-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hci', '0003_auto_20180905_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySurvey',
            fields=[
                ('participant',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='hci.Participant')),
                ('gender', models.CharField(max_length=50)),
                ('age_bracket', models.CharField(max_length=50)),
                ('mindfulness', models.CharField(max_length=50)),
                ('meditation', models.CharField(max_length=50)),
                ('meditation_tech', models.CharField(max_length=50)),
            ],
        ),
    ]
