# Generated by Django 2.1 on 2018-09-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hci', '0004_studysurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysurvey',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='age_bracket',
            field=models.CharField(
                choices=[('20_under', '20 or under'), ('21_23', '21-23'), ('24_27', '24-27'), (28, '28+')],
                max_length=50),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('custom', 'Specify')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='meditation',
            field=models.CharField(choices=[('none', 'Not at all'), ('less_1_week', 'Less than once per week'),
                                            ('1_3_week', '1-3 times per week'), ('4_7_week', '4-7 times per week'),
                                            ('multiple_day', 'Multiple times per day')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='meditation_tech',
            field=models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('always', 'Always')],
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='mindfulness',
            field=models.CharField(
                choices=[('0', 'Not at all'), ('1', 'Partially'), ('2', 'Reasonably'), ('3', 'Thoroughly')],
                max_length=50),
        ),
    ]
