# Generated by Django 2.1 on 2018-09-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hci', '0005_auto_20180907_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_control',
            field=models.BooleanField(default=False, verbose_name='Control participant'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='age_bracket',
            field=models.CharField(choices=[('20_under', '20 or under'), ('21_23', '21-23'), ('24_27', '24-27'), ('28_plus', '28+')], default=None, max_length=50, verbose_name='How old are you?'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=50, verbose_name='My gender'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('custom', 'Specify')], default=None, max_length=10, verbose_name='What is your gender?'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='meditation',
            field=models.CharField(choices=[('none', 'Not at all'), ('less_1_week', 'Less than once per week'), ('1_3_week', '1-3 times per week'), ('4_7_week', '4-7 times per week'), ('multiple_day', 'Multiple times per day')], default=None, max_length=50, verbose_name='How often do you meditate?'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='meditation_tech',
            field=models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('always', 'Always')], default=('never', 'Never'), max_length=50, verbose_name='Do you use technology to meditate?'),
        ),
        migrations.AlterField(
            model_name='studysurvey',
            name='mindfulness',
            field=models.CharField(choices=[('0', 'Not at all'), ('1', 'Partially'), ('2', 'Reasonably'), ('3', 'Thoroughly')], default=None, max_length=50, verbose_name='How well do you believe you understand mindfulness?'),
        ),
    ]
